### ISSUE TITLE
Coq Platform does not work with `make`

### ISSUE THREAD

**Issue by jwnhy** [coq/platform#224] opened 2022-03-11 14:34 UTC
I installed Coq Platform with `snapd`. It seems incompatible with the system-level `make`.

```bash
COQDEP VFILES
/bin/sh: line 1: coqdep: command not found
COQDEP VFILES
/bin/sh: line 1: coqdep: command not found
COQDEP VFILES
/bin/sh: line 1: coqdep: command not found
COQC Verif_sumarray.v
File "./Verif_sumarray.v", line 116, characters 8-18:
Error: Cannot find a physical path bound to logical path matching suffix VC.

make[1]: *** [makefile:763: Verif_sumarray.vo] Error 1
make: *** [makefile:386: all] Error 2
```

If using `coqide`'s make, everything is fine.
I am guessing it is due to some `$PATH` issue between host system and snap image.
Any ideas on how to fix this?

**Comment by Zimmi48** [comment] 2022-03-14 10:37
The issue seems to be that `coqdep` is not available in `PATH`. Snap hides most commands from the global path by sealing them into a Snap-specific namespace. But we can require global aliases and we have done so for several toplevel commands including `coqdep`: https://forum.snapcraft.io/t/aliases-request-for-coq-prover/21925/12. Since this request has been granted, it is strange that you are hitting this issue. Could it be a regression in the aliases or could it be due to your Snap environment not taking these aliases into account? I unfortunately cannot test this Snap on my side to attempt to reproduce the issue.

**Comment by MSoegtropIMC** [comment] 2022-03-14 11:18
@gares : do you have time to look into this?

**Comment by gares** [comment] 2022-03-14 12:05
No, coqdept is not an alias:
```shell
$ snap aliases coq-prover
Command                  Alias          Notes
coq-prover.coq-makefile  coq_makefile   -
coq-prover.coqc          coqc           -
coq-prover.coqide        coqide         -
coq-prover.coqidetop     coqidetop.opt  -
coq-prover.coqtop        coqtop         -
```
*but* if you use the coq_makefile from the snap, then it should pick the `coqdep` in the snap, since the, say `Makefile.conf`, should contain:
```make
COQBIN = /snap/coq-prover/28/coq-platform/2022-01-0/bin/
```
and `Makefile` should contain:
```make
# Coq binaries
COQC     ?= "$(COQBIN)coqc"
COQTOP   ?= "$(COQBIN)coqtop"
COQCHK   ?= "$(COQBIN)coqchk"
COQNATIVE ?= "$(COQBIN)coqnative"
COQDEP   ?= "$(COQBIN)coqdep"
COQDOC   ?= "$(COQBIN)coqdoc"
COQPP    ?= "$(COQBIN)coqpp"
COQMKFILE ?= "$(COQBIN)coq_makefile"
OCAMLLIBDEP ?= "$(COQBIN)ocamllibdep"
```

@Zimmi48 if you want to also ask an alias for the other binders not in this list, I'm OK with it but I don't have time right now.

**Comment by gares** [comment] 2022-03-14 12:06
@jwnhy can you confirm you did not run the `coq_makefile` from the snap package?

**Comment by gares** [comment] 2022-03-14 12:08
(also, ftr, if you install the snap by hand, eg `snap install ./my-file.snap --dangerous` then aliases are not created)

**Comment by jwnhy** [comment] 2022-03-14 12:20
> @jwnhy can you confirm you did not run the `coq_makefile` from the snap package?

Actually I tried both the original `makefile` in the SF and use `coq_makefile` to make one.

**Comment by Zimmi48** [comment] 2022-03-14 12:38
>@Zimmi48 if you want to also ask an alias for the other binaries not in this list, I'm OK with it but I don't have time right now.

You've missed my point, the link that I've provided contains:

> coqdep -> coq-prover.coqdep 

So the alias was already requested and granted, although maybe it was never correctly set up...

**Comment by gares** [comment] 2022-03-14 13:18
OK, so we have 2 problems:
- the alias request was not fulfilled
- still, even without the alias coq_makefile should work

For the second problem, @jwnhy, could you please start afresh, generate the makefile with coq_makefile from the snap and type  `make debug; make VERBOSE=1`, thanks

**Comment by jwnhy** [comment] 2022-03-14 13:45
So I ran the `make debug > ~/temp 2>&1; make VERBOSE=1 >> ~/temp 2&>1`
and it spit out a huge [chunk](https://pastebin.com/j92Qeq4z).
@gares Hope this is useful to you.

**Comment by gares** [comment] 2022-03-14 14:07
Something is very fishy, for example this does not exist:
- /snap/coq-prover/28/coq-platform/2022-01-0/bin//coqc

While your screenshot suggests that
- /var/lib/snapd/snap/coq-prover/28/coq-platform/2022-01-0/bin//coqc

does. Which Linux distro are you on? It is probably a bug of the snap package which assumes snap is installed in /snap/ but it is not the case.

**Comment by gares** [comment] 2022-03-14 14:11
@Zimmi48 the problem with aliases is probably that we don't declare a corresponding app, see
https://github.com/coq/platform/blob/88d69fcd97b313de1c6e39b9439234ad6e863f21/linux/snap/snapcraft.yaml.in#L43

**Comment by gares** [comment] 2022-03-14 17:39
`coqidetop.opt` is there, see the listing I posted above. My guess is that it won't generate an alias pointing to a non existing app.

**Comment by jwnhy** [comment] 2022-03-14 22:11
> > It took me a while to get every kernel stuff for `snap` to work...
> 
> Are the paths configured in a standard way? I don't get why coq_makefile spits path containing `/snap` (I cannot find it hardcoded anywhere).

Yes, here is my `$PATH`
```bash
/home/john/.cargo/bin:/home/john/.elan/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/13/bin:/var/lib/snapd/snap/bin:/opt/x86_64-linux-musl-cross/bin/:/home/john/Android/Sdk/platform-tools/:/home/john/tools/xfel/:/home/john/tools/bsc/bin:/opt/toolbox:/opt/arm64/bin/:/opt/riscv/bin:/home/john/tools/Xilinx/Vivado/2020.3/bin/:/home/john/.local/bin:/opt/JLink_Linux_V760b_x86_64:/opt/FreedomStudio-4.18.0.2021-04-1-x86_64-linux-ubuntu14/

```

**Comment by jwnhy** [comment] 2022-03-14 22:12
My `snap` version is 2.54.4

**Comment by MSoegtropIMC** [comment] 2022-03-21 19:01
@gares : is there something I can do for 2022.03 to improve things?

**Comment by gares** [comment] 2022-03-21 19:58
Hum, no, I'm out of ideas.

**Comment by MSoegtropIMC** [comment] 2022-03-21 20:39
OK, I postponed this and put it on my agenda to become less snap agnostic. Maybe as snap newbe I can more easily reproduce such issues than as a snap pro like you.

**Comment by gares** [comment] 2022-03-21 21:04
In thos specific case it seems a snapd with a weird path layout on a niche distribution... not exactly where I would start.

**Comment by MSoegtropIMC** [comment] 2022-03-21 21:26
Ah OK, I didn't read the Gentoo thing.

Well I would say that Gentoo doesn't really support snap and we should simply document this and recommend that users on Gentoo should use the from sources scripts.

**Comment by Zimmi48** [comment] 2022-04-14 11:13
Just for the record, while we might wish to close the "Gentoo" part of this issue as "won't fix" / unsupported, there remains the fact that some of the commands that we decided to export (at [some point](https://forum.snapcraft.io/t/aliases-request-for-coq-prover/21925/12)) are not exported because they are not listed under: https://github.com/coq/platform/blob/88d69fcd97b313de1c6e39b9439234ad6e863f21/linux/snap/snapcraft.yaml.in#L43

I think this latter part should still be fixed (for Proof General users) or documented (e.g., in the case of `coqdoc`, for which no alias was requested).

**Comment by MSoegtropIMC** [comment] 2022-04-15 17:42
@gares : isn't it so that one also needs some sort of approval from the snap team to export apps without prefix?

**Comment by gares** [comment] 2022-04-15 18:38
Yes, but Theo already did. They don't show up since there is no entry in the app: stanza, I believe.
See https://forum.snapcraft.io/t/aliases-request-for-coq-prover/21925/13

**Closed** 2022-10-05 16:35 UTC
Labels: platform: snap
