### ISSUE TITLE
Platform install into nonempty directory can fail

### ISSUE THREAD

**Issue by andrew-appel** [coq/platform#214] opened 2022-02-03 16:14 UTC
This is a more accurate description of issue #213 

The Coq 8.14 and Coq 8.15 platform installs, on Windows, can fail if they are installed into a nonempty directory that contains files from previous Coq installations.  A typical error message is,

```
$ cat <\dev\null >empty.v
$ coqc empty.v
Dynlink error: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_
dll "Failure(\"Cannot resolve camlAttributes__$2b$2b_268\")")
```

**Comment by andrew-appel** [comment] 2022-02-03 16:16
See also https://doi.org/10.1145/3497775.3503951, footnote 24.

**Comment by MSoegtropIMC** [comment] 2022-02-03 17:24
Indeed some day I wanted to switch to MSI installers, which handle version migration via a system wide database of installed modules (typically one puts each file into a module). The main downside of this is that it is a bit slow with software with so many files.

**Comment by MSoegtropIMC** [comment] 2022-09-29 17:40
This is a duplicate of #254 (or the other way around). It is fixed by giving some detailed instructions in the path selection dialog.

**Closed by MSoegtropIMC** 2022-09-29 17:40 UTC
Labels: part: installation, platform: windows
