### ISSUE TITLE
Broken installation with installer

### ISSUE THREAD

**Issue by bartlomiejkrolikowski** [coq/platform#270] opened 2022-07-03 12:31 UTC
#### Description of the problem

After installing latest version of Coq I get the following message:

> (coqide.exe:12032): GdkPixbuf-WARNING **: Cannot open pixbuf loader module file 'C:\\Coq-Platform\~8.15\~2022.04\\lib\\gdk-pixbuf-2.0\\2.10.0\\loaders.cache': No such file or directory
> 
> This likely means that your installation is broken.
> Try running the command
>   gdk-pixbuf-query-loaders > C:\\Coq-Platform\~8.15\~2022.04\\lib\\gdk-pixbuf-2.0\\2.10.0\\loaders.cache
> to make things work again for the time being.

the same with lower version:

> (coqide.exe:4012): GdkPixbuf-WARNING **: Cannot open pixbuf loader module file 'C:\\Coq-Platform\~8.14\~2022.04\\lib\\gdk-pixbuf-2.0\\2.10.0\\loaders.cache': No such file or directory
> 
> This likely means that your installation is broken.
> Try running the command
>   gdk-pixbuf-query-loaders > C:\\Coq-Platform\~8.14\~2022.04\\lib\\gdk-pixbuf-2.0\\2.10.0\\loaders.cache
> to make things work again for the time being.

running presented commands does not help
there is no directory "gdk-pixbuf-2.0" in "C:\\Coq-Platform\~8.15\~2022.04\\lib"

#### Coq Version
8.15.2 and 8.14.2
(installed with binary installer "Coq-Platform-release-2022.04.1-version_8.15_2022.04-arch-x86_64_signed.exe" on Windows 10 Home)

**Comment by MSoegtropIMC** [comment] 2022-07-03 16:38
This is a duplicate of (https://github.com/coq/platform/issues/212).

As mentioned there, CoqIDE doesn't use any dynamic pixbuf loaders (it doesn't load JPEG images and the like), so this does not hurt. Of course one could add them to silence the warning.

If you have any other issue with CoqIDE (say that it actually does not work), please create an issue describing the symptoms.

**Closed by MSoegtropIMC** 2022-07-03 16:38 UTC
