### ISSUE TITLE
Coq-Platform~8.14~2022.04.app on macOS 10.13.6

### ISSUE THREAD

**Issue by richfh** [coq/platform#256] opened 2022-04-27 18:05 UTC
Coq-Platform\~8.14\~2022.04.app does not launch on macOS 10.13.6.
Error message is:

You can't use this version of the
application "Coq-Platform\~8.14\~2022.04.app" with this version of
macOS.  You have macOS 10.13.6. The application requires macOS
11.0 or later.

**Comment by MSoegtropIMC** [comment] 2022-04-28 06:39
Duplicate of https://github.com/coq/platform/issues/220.

Since there is the alternative path of compiling from sources, I am not sure I will fix this.

**Closed by MSoegtropIMC** 2022-04-28 06:39 UTC
Labels: platform: macOS
