### ISSUE TITLE
Coq-Platform~8.14~2022.04.app on macOS 10.15.7

### ISSUE THREAD

**Issue by richfh** [coq/platform#257] opened 2022-04-27 18:10 UTC
Coq-Platform\~8.14\~2022.04.app does not launch on macOS 10.15.7.
Error message is:

You can't use this version of the application "Coq-Platform\~8.14\~2022.04.app" with this version of
macOS.  You have macOS 10.15.7. The application requires macOS 11.0 or later.

**Comment by MSoegtropIMC** [comment] 2022-04-28 06:41
I don't think you need to create an issue for each individual version.

The main question is if we do support older versions than what is supported by the XCode on the GitHub runners or not.

Duplicate of https://github.com/coq/platform/issues/220.

**Comment by richfh** [comment] 2022-04-28 12:38
I posted the additional issues because the release notes [https://github.com/coq/platform/releases/tag/2022.04.0]() say 
"Notes on the macOS installer: This installer is only compatible with macOS 10.13 or higher." (I have 10.13 and 10.15)
and also because although the binary installers for 2022.04 don't work, Coq-Platform-8.14\~2022.01.app **DOES** work on
macOS 10.15.7 (both IDE app and command line binaries). (So something changed between 2022.01 and .04.)

If macOS 11 is required to use installers that would be helpful to know.

**Comment by MSoegtropIMC** [comment] 2022-04-28 12:55
@richfh thanks for the additional information - it is helpful.

Essentially status quo is that on which OS versions the installers run depends on the version of XCode preinstalled on the MacOS runners on Github. apparently this changes without notice.

I guess we need to look into supporting older versions if only to have this under control.

**Comment by MSoegtropIMC** [comment] 2022-04-28 12:57
For the time being I updated the release notes.

**Comment by MSoegtropIMC** [comment] 2022-09-29 15:25
Duplicate of #220.

**Closed by MSoegtropIMC** 2022-09-29 15:25 UTC
