### ISSUE TITLE
[windows] findlib is not initalized correcty when called from coq-lsp

### ISSUE THREAD

**Issue by ejgallego** [coq/platform#332] opened 2023-02-21 18:25 UTC
When running coq-lsp in a Platform opam switch, findlib configuration seems broken.

This can be fixed by passing the right `--ocamlpath=$dir` option to coq-lsp, however it'd be nice if we could patch `coq-lsp` to figure this automatically and be more compatible with the Windows Platform.

**Comment by MSoegtropIMC** [comment] 2023-04-06 09:36
To make findlib work after installation (=relocation), I am using a modification to it which works as follows:

- there is a file "findlib.root" in the Coq Platform installation root folder.
- executables search the directory tree upwards from their own folder until they find "findlib.root" or /.
- the findlib root folder is compiled into the executables relative to the folder found above.

This patch is used in both "compile from sources" and "installed" mode (since the installer is made from a "compile from sources" installation without extra options).

So for this to work, your executable must be somewhere under the Coq Platform install folder.

If you want to install something outside of the Coq Platform installation - which is not a supported use case - what might work is to create a findlib.root file in your installation and symlink the findlib folder in the appropriate place relative to findlib.root in your installation. But I would rather recommend to deliver coq-lsp with Coq Platform, which would solve all these issues.

I don't see any other way to make multiple installations for Coq Platform coexist on one machine.

Please close, if this works for you, otherwise we should discuss on Zulip.

**Comment by MSoegtropIMC** [comment] 2024-07-12 14:14
Triage note: closing because things work as expected.

**Closed by MSoegtropIMC** 2024-07-12 14:14 UTC
Labels: solution: wontfix

**Comment by ejgallego** [comment] 2024-07-12 14:29
I think this is still not working as expected, how did you test?

**Comment by MSoegtropIMC** [comment] 2024-07-12 16:01
@ejgallego : as explained I think the problem is that you expect that Coq Platform binaries work out of its tree. This is not the case. The findlib has a patch to make it relocatable and this patch requires that the binary calling findlib is in a directory above the findlib.root file. Since the installation has to be relocatable I cannot compile a fixed library path into it.

If you have other suggestions on how to make a Coq Platform installation relocatable I am open to it (there are actually more mechanisms like a installer created init file with paths). But there is simply no way to find the installation from arbitrary locations. Your usage of Coq Platform findlib is simply out of spec.

**Comment by ejgallego** [comment] 2024-07-12 16:25
How is my usage out of spec?

I place the binary along `coqc` and all the others.

**Comment by ejgallego** [comment] 2024-07-12 16:26
What I observed is that placing the binary there, still the findlib config for some reason was not right.

Actually this could be broken for all other binaries too, as only very recently some other packages that make effective use of findlib were added / updated.

I am not sure what the current status of this bug is tho, I did the testing a long time ago.
