### ISSUE TITLE
Coq-Platform~8.15~2022.04.app on macOS 10.15.7

### ISSUE THREAD

**Issue by richfh** [coq/platform#258] opened 2022-04-27 18:12 UTC
Coq-Platform\~8.15\~2022.04.app does not launch on macOS 10.15.7.
Error message is:

You can't use this version of the application "Coq-Platform\~8.15\~2022.04.app" with this version of macOS.  
You have macOS 10.15.7. The application requires macOS 11.0 or later.

**Comment by MSoegtropIMC** [comment] 2022-04-28 06:41
Duplicate of https://github.com/coq/platform/issues/220.

**Closed by MSoegtropIMC** 2022-04-28 06:41 UTC
